.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. russianbitcoin_qt test_russianbitcoin_qt
clean: FORCE
	$(MAKE) -C .. russianbitcoin_qt_clean test_russianbitcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_russianbitcoin_qt_check
russianbitcoin-qt russianbitcoin-qt.exe: FORCE
	 $(MAKE) -C .. russianbitcoin_qt
